a = input('Digite algo: ')
print('O tipo primitivo é {}'.format(type(a)))
print('Só tem espaços? {}'.format(a.isspace()))
print('É um número? {}'.format(a.isnumeric()))
print('É alfabeto? {}'.format(a.isalpha()))
print('É alfanumérico? {}'.format(a.isalnum()))
print('Esta em Maiúscula? {}'.format(a.isupper()))
print('Esta em Minúscula {}'.format(a.islower()))
print('Está capitalizado? {}'.format(a.istitle()))
